# -*- coding: utf-8 -*-
"""AIR QUALITY FORECASTING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d0GDtVap0ZD8HE3uoTmCMnsEb-RwzCnY
"""

import numpy as np
import pandas as pd

air_quality_data = pd.read_csv('/content/AirQualityUCI.csv')

# printing the first five rows of the data frame
air_quality_data.head()

# removing the last two coloums from the data frame
air_quality_data = air_quality_data.iloc[:,:-2] #data slicing

air_quality_data.head()

air_quality_data.tail() #last five rows

air_quality_data.loc[9353]

air_quality_data.shape



air_quality_data.info()

air_quality_data.isnull().sum() #null values

air_quality_data.isin([-200]).sum(axis=0) #missing values

"""**FORECASTING AND REGRESSION **"""

air_quality_data.isnull().sum()

# converting the date from DDMMYYYY TO YYYY MM DD
data_info = pd.to_datetime(air_quality_data['Date'])
print(data_info)

time_info = pd.to_datetime(air_quality_data['Time'])
print(time_info)

print(time_info)

print(type(data_info))
print(type(time_info))

#combing  2 series to a pandas dataframe
data_time = pd.concat([data_info,time_info],axis=1)

data_time.head()

data_time['ds']= data_time['Date'].astype(str)+' '+data_time['Time'].astype(str)

data_time.head()



"""we have to convert ds from object data type to date time format

"""

data = pd.DataFrame()

data['y'] = air_quality_data['RH']

! pip install fbprophet

from prophet import Prophet

future = model.make_future_dataframe(periods=365, freq='H')
future.tail()